# Generated by Django 4.1.6 on 2023-02-10 18:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadJoke',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=75)),
                ('setup', models.TextField()),
                ('punchline', models.TextField()),
            ],
        ),
    ]
